apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: docker.io/tax525/cowweb
    workspace: .
    docker:
      dockerfilePath: ./kubernetes/container/Dockerfile_dev
  local:
    skipPush: true
deploy:
  helm:
    releases:
    - name: cowweb-helm-dev
      chartPath: kubernetes/helm
      namespace: cowweb-dev
      values:
        image: docker.io/tax525/cowweb
#      valuesFilePath: kubernetes/dev/helm-values.yaml
      setValues:
        replicaCount: 1
        ingress.enabled: false
        http.port: 8080
        http.nodePort: 30080
        debug.enabled: true
        debug.port: 8081
        debug.nodePort: 30081
profiles:
  - name: release
    build:
      artifacts:
      - imageName: gcr.io/neseng-eq1/sample-frontend:latest
        workspace: .
        docker:
          dockerfilePath: ./kubernetes/container/Dockerfile_release
      local:
        skipPush: false
      tagPolicy:
        gitCommit: {}
    deploy:
      helm:
        releases:
        - name: cowweb-helm-release
          chartPath: kubernetes/helm
          namespace: cowweb-release
          values:
            image: gcr.io/neseng-eq1/sample-frontend:latest
          setValues:
            replicaCount: 2
            ingress.enabled: true
            http.port: 80
            http.targetPort:
            debug.enabled: false
